name: google-mint
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py313hd6074c6_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py313h18e8e13_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py313hf159716_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py313hf46b229_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyh8f84b5b_1
  - cryptography=46.0.4=py313heb322e3_0
  - frozenlist=1.7.0=py313h6b9daa2_0
  - google-api-core=2.29.0=pyhd8ed1ab_0
  - google-api-python-client=2.188.0=pyh332efcf_0
  - google-auth=2.48.0=pyhcf101f3_0
  - google-auth-httplib2=0.3.0=pyhd8ed1ab_0
  - google-auth-oauthlib=0.5.3=pyhd8ed1ab_0
  - googleapis-common-protos=1.72.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httplib2=0.31.2=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libabseil=20260107.0=cxx17_h7b12aa8_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libgcc=15.2.0=he0feb66_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - libmpdec=4.0.0=hb03c661_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.2=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libzlib=1.3.1=hb9d3cd8_2
  - multidict=6.7.0=py313h3dea7bd_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.2=py313hf6604e3_1
  - oauthlib=3.3.1=pyhd8ed1ab_0
  - openssl=3.6.1=h35e630c_1
  - pandas=3.0.0=py313hbfd7664_0
  - pip=25.3=pyh145f28c_0
  - propcache=0.3.1=py313h8060acc_0
  - proto-plus=1.27.0=pyhd8ed1ab_0
  - protobuf=6.33.5=py313hf481762_0
  - pyasn1=0.6.2=pyhd8ed1ab_0
  - pyasn1-modules=0.4.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pyjwt=2.11.0=pyhd8ed1ab_0
  - pyopenssl=25.3.0=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.11=hc97d973_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=8_cp313
  - pyu2f=0.1.5=pyhd8ed1ab_1
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - requests-oauthlib=2.0.0=pyhd8ed1ab_1
  - rsa=4.9.1=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - tk=8.6.13=noxft_h366c992_103
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - uritemplate=4.2.0=pyhd8ed1ab_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - yarl=1.22.0=py313h3dea7bd_0
  - zstd=1.5.7=hb78ec9c_6
prefix: /home/madeline/anaconda3/envs/google-mint
